name:METRICS API, path:/apps/opt/application/smartdq/dq_api/api_logs/metrics_logs/metrics_logs_2025-03-20-07-46-47.log
[2025-03-20 07:46:52 +0000] [1728448] [ERROR] Error handling request /mle/ExecuteHistorySQL/
Traceback (most recent call last):
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    callback, callback_args, callback_kwargs = self.resolve_request(request)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 313, in resolve_request
    resolver_match = resolver.resolve(request.path_info)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/urls/resolvers.py", line 663, in resolve
    for pattern in self.url_patterns:
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/apps/opt/application/smartdq/dq_api/dqaas_api/urls.py", line 24, in <module>
    path('', include('ui.urls')),
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/urls/conf.py", line 38, in include
    urlconf_module = import_module(urlconf_module)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/apps/opt/application/smartdq/dq_api/ui/urls.py", line 6, in <module>
    from MLE import views as MLE_views
  File "/apps/opt/application/smartdq/dq_api/MLE/views.py", line 549, in <module>
    import load_result_to_bq as load_bq
ModuleNotFoundError: No module named 'load_result_to_bq'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/utils/deprecation.py", line 134, in __call__
    response = response or self.get_response(request)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 57, in inner
    response = response_for_exception(request, exc)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 140, in response_for_exception
    response = handle_uncaught_exception(
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 181, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/views/debug.py", line 67, in technical_500_response
    html = reporter.get_traceback_html()
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/views/debug.py", line 410, in get_traceback_html
    c = Context(self.get_traceback_data(), use_l10n=False)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/views/debug.py", line 393, in get_traceback_data
    c["raising_view_name"] = get_caller(self.request)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/views/debug.py", line 100, in get_caller
    resolver_match = resolve(request.path)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/urls/base.py", line 24, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/urls/resolvers.py", line 663, in resolve
    for pattern in self.url_patterns:
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/apps/opt/application/smartdq/dq_api/dqaas_api/urls.py", line 24, in <module>
    path('', include('ui.urls')),
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/urls/conf.py", line 38, in include
    urlconf_module = import_module(urlconf_module)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/apps/opt/application/smartdq/dq_api/ui/urls.py", line 6, in <module>
    from MLE import views as MLE_views
  File "/apps/opt/application/smartdq/dq_api/MLE/views.py", line 549, in <module>
    import load_result_to_bq as load_bq
ModuleNotFoundError: No module named 'load_result_to_bq'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/utils/deprecation.py", line 134, in __call__
    response = response or self.get_response(request)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 57, in inner
    response = response_for_exception(request, exc)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 140, in response_for_exception
    response = handle_uncaught_exception(
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 181, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/views/debug.py", line 67, in technical_500_response
    html = reporter.get_traceback_html()
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/views/debug.py", line 410, in get_traceback_html
    c = Context(self.get_traceback_data(), use_l10n=False)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/views/debug.py", line 393, in get_traceback_data
    c["raising_view_name"] = get_caller(self.request)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/views/debug.py", line 100, in get_caller
    resolver_match = resolve(request.path)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/urls/base.py", line 24, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/urls/resolvers.py", line 663, in resolve
    for pattern in self.url_patterns:
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/apps/opt/application/smartdq/dq_api/dqaas_api/urls.py", line 24, in <module>
    path('', include('ui.urls')),
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/urls/conf.py", line 38, in include
    urlconf_module = import_module(urlconf_module)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/apps/opt/application/smartdq/dq_api/ui/urls.py", line 6, in <module>
    from MLE import views as MLE_views
  File "/apps/opt/application/smartdq/dq_api/MLE/views.py", line 549, in <module>
    import load_result_to_bq as load_bq
ModuleNotFoundError: No module named 'load_result_to_bq'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/utils/deprecation.py", line 134, in __call__
    response = response or self.get_response(request)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 57, in inner
    response = response_for_exception(request, exc)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 140, in response_for_exception
    response = handle_uncaught_exception(
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 181, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/views/debug.py", line 67, in technical_500_response
    html = reporter.get_traceback_html()
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/views/debug.py", line 410, in get_traceback_html
    c = Context(self.get_traceback_data(), use_l10n=False)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/views/debug.py", line 393, in get_traceback_data
    c["raising_view_name"] = get_caller(self.request)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/views/debug.py", line 100, in get_caller
    resolver_match = resolve(request.path)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/urls/base.py", line 24, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/urls/resolvers.py", line 663, in resolve
    for pattern in self.url_patterns:
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/apps/opt/application/smartdq/dq_api/dqaas_api/urls.py", line 24, in <module>
    path('', include('ui.urls')),
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/urls/conf.py", line 38, in include
    urlconf_module = import_module(urlconf_module)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/apps/opt/application/smartdq/dq_api/ui/urls.py", line 6, in <module>
    from MLE import views as MLE_views
  File "/apps/opt/application/smartdq/dq_api/MLE/views.py", line 549, in <module>
    import load_result_to_bq as load_bq
ModuleNotFoundError: No module named 'load_result_to_bq'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/utils/deprecation.py", line 134, in __call__
    response = response or self.get_response(request)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 57, in inner
    response = response_for_exception(request, exc)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 140, in response_for_exception
    response = handle_uncaught_exception(
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 181, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/views/debug.py", line 67, in technical_500_response
    html = reporter.get_traceback_html()
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/views/debug.py", line 410, in get_traceback_html
    c = Context(self.get_traceback_data(), use_l10n=False)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/views/debug.py", line 393, in get_traceback_data
    c["raising_view_name"] = get_caller(self.request)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/views/debug.py", line 100, in get_caller
    resolver_match = resolve(request.path)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/urls/base.py", line 24, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/urls/resolvers.py", line 663, in resolve
    for pattern in self.url_patterns:
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/apps/opt/application/smartdq/dq_api/dqaas_api/urls.py", line 24, in <module>
    path('', include('ui.urls')),
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/urls/conf.py", line 38, in include
    urlconf_module = import_module(urlconf_module)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/apps/opt/application/smartdq/dq_api/ui/urls.py", line 6, in <module>
    from MLE import views as MLE_views
  File "/apps/opt/application/smartdq/dq_api/MLE/views.py", line 549, in <module>
    import load_result_to_bq as load_bq
ModuleNotFoundError: No module named 'load_result_to_bq'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/utils/deprecation.py", line 134, in __call__
    response = response or self.get_response(request)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 57, in inner
    response = response_for_exception(request, exc)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 140, in response_for_exception
    response = handle_uncaught_exception(
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 181, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/views/debug.py", line 67, in technical_500_response
    html = reporter.get_traceback_html()
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/views/debug.py", line 410, in get_traceback_html
    c = Context(self.get_traceback_data(), use_l10n=False)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/views/debug.py", line 393, in get_traceback_data
    c["raising_view_name"] = get_caller(self.request)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/views/debug.py", line 100, in get_caller
    resolver_match = resolve(request.path)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/urls/base.py", line 24, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/urls/resolvers.py", line 663, in resolve
    for pattern in self.url_patterns:
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/apps/opt/application/smartdq/dq_api/dqaas_api/urls.py", line 24, in <module>
    path('', include('ui.urls')),
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/urls/conf.py", line 38, in include
    urlconf_module = import_module(urlconf_module)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/apps/opt/application/smartdq/dq_api/ui/urls.py", line 6, in <module>
    from MLE import views as MLE_views
  File "/apps/opt/application/smartdq/dq_api/MLE/views.py", line 549, in <module>
    import load_result_to_bq as load_bq
ModuleNotFoundError: No module named 'load_result_to_bq'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/utils/deprecation.py", line 134, in __call__
    response = response or self.get_response(request)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 57, in inner
    response = response_for_exception(request, exc)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 140, in response_for_exception
    response = handle_uncaught_exception(
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 181, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/views/debug.py", line 67, in technical_500_response
    html = reporter.get_traceback_html()
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/views/debug.py", line 410, in get_traceback_html
    c = Context(self.get_traceback_data(), use_l10n=False)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/views/debug.py", line 393, in get_traceback_data
    c["raising_view_name"] = get_caller(self.request)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/views/debug.py", line 100, in get_caller
    resolver_match = resolve(request.path)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/urls/base.py", line 24, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/urls/resolvers.py", line 663, in resolve
    for pattern in self.url_patterns:
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/apps/opt/application/smartdq/dq_api/dqaas_api/urls.py", line 24, in <module>
    path('', include('ui.urls')),
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/urls/conf.py", line 38, in include
    urlconf_module = import_module(urlconf_module)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/apps/opt/application/smartdq/dq_api/ui/urls.py", line 6, in <module>
    from MLE import views as MLE_views
  File "/apps/opt/application/smartdq/dq_api/MLE/views.py", line 549, in <module>
    import load_result_to_bq as load_bq
ModuleNotFoundError: No module named 'load_result_to_bq'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/utils/deprecation.py", line 134, in __call__
    response = response or self.get_response(request)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 57, in inner
    response = response_for_exception(request, exc)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 140, in response_for_exception
    response = handle_uncaught_exception(
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 181, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/views/debug.py", line 67, in technical_500_response
    html = reporter.get_traceback_html()
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/views/debug.py", line 410, in get_traceback_html
    c = Context(self.get_traceback_data(), use_l10n=False)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/views/debug.py", line 393, in get_traceback_data
    c["raising_view_name"] = get_caller(self.request)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/views/debug.py", line 100, in get_caller
    resolver_match = resolve(request.path)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/urls/base.py", line 24, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/urls/resolvers.py", line 663, in resolve
    for pattern in self.url_patterns:
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/apps/opt/application/smartdq/dq_api/dqaas_api/urls.py", line 24, in <module>
    path('', include('ui.urls')),
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/urls/conf.py", line 38, in include
    urlconf_module = import_module(urlconf_module)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/apps/opt/application/smartdq/dq_api/ui/urls.py", line 6, in <module>
    from MLE import views as MLE_views
  File "/apps/opt/application/smartdq/dq_api/MLE/views.py", line 549, in <module>
    import load_result_to_bq as load_bq
ModuleNotFoundError: No module named 'load_result_to_bq'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/corsheaders/middleware.py", line 56, in __call__
    result = self.get_response(request)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 57, in inner
    response = response_for_exception(request, exc)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 140, in response_for_exception
    response = handle_uncaught_exception(
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 181, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/views/debug.py", line 67, in technical_500_response
    html = reporter.get_traceback_html()
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/views/debug.py", line 410, in get_traceback_html
    c = Context(self.get_traceback_data(), use_l10n=False)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/views/debug.py", line 393, in get_traceback_data
    c["raising_view_name"] = get_caller(self.request)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/views/debug.py", line 100, in get_caller
    resolver_match = resolve(request.path)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/urls/base.py", line 24, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/urls/resolvers.py", line 663, in resolve
    for pattern in self.url_patterns:
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/apps/opt/application/smartdq/dq_api/dqaas_api/urls.py", line 24, in <module>
    path('', include('ui.urls')),
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/urls/conf.py", line 38, in include
    urlconf_module = import_module(urlconf_module)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/apps/opt/application/smartdq/dq_api/ui/urls.py", line 6, in <module>
    from MLE import views as MLE_views
  File "/apps/opt/application/smartdq/dq_api/MLE/views.py", line 549, in <module>
    import load_result_to_bq as load_bq
ModuleNotFoundError: No module named 'load_result_to_bq'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/gunicorn/workers/sync.py", line 134, in handle
    self.handle_request(listener, req, client, addr)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/gunicorn/workers/sync.py", line 177, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/core/handlers/wsgi.py", line 124, in __call__
    response = self.get_response(request)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 140, in get_response
    response = self._middleware_chain(request)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 57, in inner
    response = response_for_exception(request, exc)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 140, in response_for_exception
    response = handle_uncaught_exception(
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 181, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/views/debug.py", line 67, in technical_500_response
    html = reporter.get_traceback_html()
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/views/debug.py", line 410, in get_traceback_html
    c = Context(self.get_traceback_data(), use_l10n=False)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/views/debug.py", line 393, in get_traceback_data
    c["raising_view_name"] = get_caller(self.request)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/views/debug.py", line 100, in get_caller
    resolver_match = resolve(request.path)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/urls/base.py", line 24, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/urls/resolvers.py", line 663, in resolve
    for pattern in self.url_patterns:
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/apps/opt/application/smartdq/dq_api/dqaas_api/urls.py", line 24, in <module>
    path('', include('ui.urls')),
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/site-packages/django/urls/conf.py", line 38, in include
    urlconf_module = import_module(urlconf_module)
  File "/apps/opt/application/smartdq/envs/smartdq-venv/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/apps/opt/application/smartdq/dq_api/ui/urls.py", line 6, in <module>
    from MLE import views as MLE_views
  File "/apps/opt/application/smartdq/dq_api/MLE/views.py", line 549, in <module>
    import load_result_to_bq as load_bq
ModuleNotFoundError: No module named 'load_result_to_bq'
